"""initial migration

Revision ID: 4bdc34bfd86c
Revises: 
Create Date: 2025-10-21 11:38:15.651164

"""
from typing import Sequence, Union

from alembic import op
from app.models.user import UserRole
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdc34bfd86c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'CANDIDAT', 'RECRUTEUR', name='userrole'),
            nullable=False,
            server_default='CANDIDAT'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
